version: '3'
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"
      - "443:443"

    volumes:
       - /etc/letsencrypt/archive/petfinder.site/:/etc/nginx/certs/

    depends_on:
      - frontend
      - api

  frontend:
    build: ./frontend_service/

  api:
    build: ./api_service/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
    - /media/photos:/media/photos

  webhook:
    build: ./webhook_service/
    env_file:
      - .env
    depends_on:
      - redis

  tgbot:
    build: ./tgbot_service/
    env_file:
      - .env
    depends_on:
      - redis
      - api

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432" # Cancel host port binding on prod
    volumes:
    - ./db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: isntthispasswordhard?

  redis:
    image: redis
